### ISSUE TITLE
error when using the bearings and distance tool

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#32]
# Problem
When using the manage bearings and distances I get the following error

```
An error has occurred while executing Python code: 

TypeError: QStringListModel.setStringList(QStringList): argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/parcel_plugin/plugin.py", line 287, in manageBearDist
    BearDistManager(self.iface, self.db, self.requiredLayers)
  File "/home/admire/.qgis2/python/plugins/parcel_plugin/plugin.py", line 562, in __init__
    self.run()
  File "/home/admire/.qgis2/python/plugins/parcel_plugin/plugin.py", line 571, in run
    self.requiredLayers
  File "/home/admire/.qgis2/python/plugins/parcel_plugin/PyQt4Dialogs.py", line 901, in __init__
    self.initItemSurveyPlan()
  File "/home/admire/.qgis2/python/plugins/parcel_plugin/PyQt4Dialogs.py", line 937, in initItemSurveyPlan
    model.setStringList(self.auto["SURVEYPLAN"])
TypeError: QStringListModel.setStringList(QStringList): argument 1 has unexpected type 'NoneType'
```

# Solution
Make it happy

**Comment by NyakudyaA** [comment]
@gubuntu  I will close this ticket after your comments. 

![edit-2](https://user-images.githubusercontent.com/2510900/26884938-5b558eb8-4ba1-11e7-983b-e2c212643691.gif)


 
This error is caused by a user not populating the survey table initially. I think the main issue should be.
* When a survey table is empty the bearing and distance tool should be grayed and give an informative message.
* When a user clicks on the bearings and distance when the survey table is empty instead of an error message we open up the attribute table for editing. 
* Or we could have triggers that auto populates the survey table with the mandatory information once a principal beacon has been captured.

**Comment by gubuntu** [comment]
Also make it clear in the use manual that a survey must be captured first...along with explaining what a survey is and why it needs to be captured.

**Comment by gubuntu** [comment]
On my Mc, when I tried to capture bearings and distances when there was no survey record in the survey table, nothing happened. On Ubuntu a Python error passed the database error about no survey bit on a Mac, nothing. An informative error should pop ip.
