### ISSUE TITLE
qgis error when i click on Manage Bearing & Distances

### ISSUE THREAD

**Issue by holysanta** [kartoza/parcel_plugin#53]
Traceback (most recent call last):
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 287, in manageBearDist
			    BearDistManager(self.iface, self.db, self.requiredLayers)
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 562, in __init__
			    self.run()
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 571, in run
			    self.requiredLayers
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\PyQt4Dialogs.py", line 901, in __init__
			    self.initItemSurveyPlan()
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\PyQt4Dialogs.py", line 937, in initItemSurveyPlan
			    model.setStringList(self.auto["SURVEYPLAN"])
			TypeError: QStringListModel.setStringList(QStringList): argument 1 has unexpected type 'NoneType'

**Comment by NyakudyaA** [comment]
@holysanta  This usually occurs due to user input error. You cannot use the bearings and distances when you have not populated the following tables `beacons,scheme,survey` in that order. For now we are going to insert dummy data so that the following error does not appear. @myarjunar  how easy is it to grey out the bearings and distances icon if the `survey ` table is empty

**Comment by NyakudyaA** [comment]
The bearings and distance tool is greyed out by default when the survey table is empty. These forces users to populate it
