### ISSUE TITLE
Error during compose new parcel

### ISSUE THREAD

**Issue by holysanta** [kartoza/parcel_plugin#54]
I get this error when i click save after selecting beacons (create new parcel) and plugin crashes and refuses to reload afterwards

2017-12-12T01:48:04	1	Traceback (most recent call last):
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 274, in manageParcels
			    ParcelManager(self.iface, self.db, self.requiredLayers)
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 431, in __init__
			    self.run()
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 471, in run
			    self.db.query(sql)
			  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\database.py", line 85, in query
			    raise Exception('Backend database query failed!\nError raised: %s.' %(str(e),))
			Exception: Backend database query failed!
			Error raised: cannot refresh materialized view "public.boundaries" concurrently
			HINT:  Create a unique index with no WHERE clause on one or more columns of the materialized view.
			CONTEXT:  SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY boundaries"
			PL/pgSQL function boundaries_views() line 3 at SQL statement
			.

**Comment by NyakudyaA** [comment]
@holysanta Please make sure you are using the correct version of the script for setting up the database.
https://github.com/kartoza/parcel_plugin/blob/master/scripts/database_setup.sql#L1754
